////------------------------------------------------------------------------------
//// <autogenerated>
////     This code was generated by a tool.
////     Generated by Merlin Version: 1.0.0.0
////
////     Changes to this file may cause incorrect behavior and will be lost if 
////     the code is regenerated.
//// </autogenerated>
////------------------------------------------------------------------------------
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Net;
//using System.Net.Http;
//using System.Web.Http;
//using Microsoft.VisualStudio.TestTools.UnitTesting;
//using Moq;
//using LucentDb.Data.Repository;
//using LucentDb.Domain.Entities;
//using LucentDb.Web.UI.Controllers.Api;

//namespace LucentDb.Web.UI.Test.Controllers.Api
//{
//    [TestFixture()]
//    public class ConnectionProviderApiControllerTests
//    {

//        private Mock<IConnectionProviderRepository> _repository;

//        private List<ConnectionProvider> _repositoryList = new List<ConnectionProvider>
//        {
//        //TODO Initialize test data
//            new ConnectionProvider()
//        };

//        private ConnectionProviderApiController _target;

//        [TestInitialize]
//        public void Init()
//        {
//            _repository = new Mock<IConnectionProviderRepository>();
//            _target = new ConnectionProviderApiController(_repository.Object)
//            {
//                Request = new HttpRequestMessage { RequestUri = new Uri("http://localhost/api/ConnectionProviders") }
//            };

//            var config = new HttpConfiguration();

//            config.MapHttpAttributeRoutes();
//            config.EnsureInitialized();

//            _target.Request.SetConfiguration(config);
//        }

//                [Test()]
//        public void GetDataTest() 
//        {
//            _repository
//                 .Setup(it => it.GetData())
//                     .Returns(_repositoryList);

//            var result = _target.GetData().ToList();
//             Assert.AreEqual(_repositoryList.ToList().Count, result.Count);
//        }

//        [Test()]
//        public void Update_Should_Update_A_ConnectionProvider() 
//        {
//            _repository
//                 .Setup(it => it.Update(It.IsAny<String>(), It.IsAny<String>(), It.IsAny<Int32>()))
//                 .Callback<String, String, Int32>((name, value, id) => 
//            { 
//                 var tConnectionProvider = _repositoryList.Find(x => x.Id==id);
//                 tConnectionProvider.Name = name; 
//                 tConnectionProvider.Value = value; 
//            });
//            var tempConnectionProvider = _repositoryList.Find(x => x.Id==id);
//            var testConnectionProvider = new ConnectionProvider {
//                 Id = tempConnectionProvider.Id, 
//                 Name = tempConnectionProvider.Name, 
//                 Value = tempConnectionProvider.Value};

//            //TODO change something on testConnectionProvider
//            //testConnectionProvider.oldValue = newValue; 
//            _target.Update(testConnectionProvider);
//            //Assert.AreEqual(newValue, _repositoryList.Find(x => x.Id==1).oldValue);
//            //TODO fail until we update the test above
//            Assert.Fail();
//        }

//        [Test()]
//        public void Delete_Should_Delete_A_ConnectionProvider() 
//        {
//            _repository
//                 .Setup(it => it.Delete(It.IsAny<Int32>()))  
//                 .Callback<Int32>((id) => 
//                 { 
//                      var i = _repositoryList.FindIndex(q => q.Id==id);
//                      _repositoryList.RemoveAt(i);
//                 });
//            var iniCount = _repositoryList.Count();
//            HttpResponseMessage result = _target.Delete(1);
//            Assert.AreEqual(iniCount - 1, _repositoryList.Count());
//            Assert.AreEqual(HttpStatusCode.OK, result.StatusCode);
//        }

//        [Test()]
//        public void Insert_Should_Insert_A_ConnectionProvider() 
//        {
//            _repository
//                 .Setup(it => it.Insert(It.IsAny<String>(), It.IsAny<String>()))
//                 .Returns<String, String>((name, value) => 
//            { 
//                 _repositoryList.Add(new  ConnectionProvider (name, value));
//            });

//            //TODO insert values 
//            _target.Insert(new ConnectionProvider (name, value));
//            //Assert.AreEqual(11, _repositoryList.Count());
//            //TODO fail until we update the test above
//            Assert.Fail();
//        }

//        [Test()]
//        public void GetDataPageableTest()
//        {
//            PagedResult<ConnectionProvider> expectedResult;

//            _repository
//                 .Setup(it => it.GetDataPageable(It.IsAny<String>(), It.IsAny<Int32>(), It.IsAny<Int32>()))
//                 .Returns<String, Int32, Int32>((sortExpression, page, pageSize) => 
//                 { 
//                      var query = _repositoryList;
//                      switch (sortExpression)
//                      {
//                          case  "Id":
//                              query = new List<ConnectionProvider>(query.OrderBy(q => q.Id));
//                              break;
//                          case  "Name":
//                              query = new List<ConnectionProvider>(query.OrderBy(q => q.Name));
//                              break;
//                          case  "Value":
//                              query = new List<ConnectionProvider>(query.OrderBy(q => q.Value));
//                              break;                      }
//                      return query.Take(pageSize).Skip((page-1)*pageSize).ToList();
//                 });

//            _repository
//                 .Setup(it => it.GetRowCount())
//                 .Returns(_repositoryList.Count);

//            var result = _target.GetDataPageable("Id", 1, 2);
//            Assert.IsTrue(result.TryGetContentValue(out expectedResult));
//            Assert.AreEqual(_repositoryList.Take(2).ToList().Count, expectedResult.Results.Count);
//            Assert.AreEqual(_repositoryList.OrderBy(q => q.Id).FirstOrDefault().Id, expectedResult.Results.FirstOrDefault().Id);
//        }

//        [Test()]
//        public void GetDataByIdTest() 
//        {
//            _repository
//                 .Setup(it => it.GetDataById(It.IsAny<Int32>()))
//                     .Returns<Int32>((id) => 
//                 { 
//                      return _repositoryList.Where(x => x.Id==id).ToList();
//                 });

//            var result = _target.GetDataById(idValue).ToList();
//             Assert.AreEqual(_repositoryList.Where(x => x.Id==idValue).ToList().Count, result.Count);
//        }


//    }
//}

