////------------------------------------------------------------------------------
//// <autogenerated>
////     This code was generated by a tool.
////     Generated by Merlin Version: 1.0.0.0
////
////     Changes to this file may cause incorrect behavior and will be lost if 
////     the code is regenerated.
//// </autogenerated>
////------------------------------------------------------------------------------
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Net;
//using System.Net.Http;
//using System.Web.Http;
//using Microsoft.VisualStudio.TestTools.UnitTesting;
//using Moq;
//using LucentDb.Data.Repository;
//using LucentDb.Domain.Entities;
//using LucentDb.Web.UI.Controllers.Api;

//namespace LucentDb.Web.UI.Test.Controllers.Api
//{
//    [TestFixture()]
//    public class TestGroupApiControllerTests
//    {
        
//        private Mock<ITestGroupRepository> _repository;

//        private List<TestGroup> _repositoryList = new List<TestGroup>
//        {
//        //TODO Initialize test data
//            new TestGroup()
//        };

//        private TestGroupApiController _target;
        
//        [TestInitialize]
//        public void Init()
//        {
//            _repository = new Mock<ITestGroupRepository>();
//            _target = new TestGroupApiController(_repository.Object)
//            {
//                Request = new HttpRequestMessage { RequestUri = new Uri("http://localhost/api/TestGroups") }
//            };

//            var config = new HttpConfiguration();

//            config.MapHttpAttributeRoutes();
//            config.EnsureInitialized();

//            _target.Request.SetConfiguration(config);
//        }
   
//                [Test()]
//        public void GetDataTest() 
//        {
//            _repository
//                 .Setup(it => it.GetData())
//                     .Returns(_repositoryList);
                
//            var result = _target.GetData().ToList();
//             Assert.AreEqual(_repositoryList.ToList().Count, result.Count);
//        }

//        [Test()]
//        public void Update_Should_Update_A_TestGroup() 
//        {
//            _repository
//                 .Setup(it => it.Update(It.IsAny<Int32>(), It.IsAny<String>(), It.IsAny<Boolean>(), It.IsAny<Int32>()))
//                 .Callback<Int32, String, Boolean, Int32>((projectId, name, isActive, id) => 
//            { 
//                 var tTestGroup = _repositoryList.Find(x => x.Id==id);
//                 tTestGroup.ProjectId = projectId; 
//                 tTestGroup.Name = name; 
//                 tTestGroup.IsActive = isActive; 
//            });
//            var tempTestGroup = _repositoryList.Find(x => x.Id==id);
//            var testTestGroup = new TestGroup {
//                 Id = tempTestGroup.Id, 
//                 ProjectId = tempTestGroup.ProjectId, 
//                 Name = tempTestGroup.Name, 
//                 IsActive = tempTestGroup.IsActive};
            
//            //TODO change something on testTestGroup
//            //testTestGroup.oldValue = newValue; 
//            _target.Update(testTestGroup);
//            //Assert.AreEqual(newValue, _repositoryList.Find(x => x.Id==1).oldValue);
//            //TODO fail until we update the test above
//            Assert.Fail();
//        }

//        [Test()]
//        public void Delete_Should_Delete_A_TestGroup() 
//        {
//            _repository
//                 .Setup(it => it.Delete(It.IsAny<Int32>()))  
//                 .Callback<Int32>((id) => 
//                 { 
//                      var i = _repositoryList.FindIndex(q => q.Id==id);
//                      _repositoryList.RemoveAt(i);
//                 });
//            var iniCount = _repositoryList.Count();
//            HttpResponseMessage result = _target.Delete(1);
//            Assert.AreEqual(iniCount - 1, _repositoryList.Count());
//            Assert.AreEqual(HttpStatusCode.OK, result.StatusCode);
//        }

//        [Test()]
//        public void Insert_Should_Insert_A_TestGroup() 
//        {
//            _repository
//                 .Setup(it => it.Insert(It.IsAny<Int32>(), It.IsAny<String>(), It.IsAny<Boolean>()))
//                 .Returns<Int32, String, Boolean>((projectId, name, isActive) => 
//            { 
//                 _repositoryList.Add(new  TestGroup (projectId, name, isActive));
//            });
            
//            //TODO insert values 
//            _target.Insert(new TestGroup (projectId, name, isActive));
//            //Assert.AreEqual(11, _repositoryList.Count());
//            //TODO fail until we update the test above
//            Assert.Fail();
//        }

//        [Test()]
//        public void GetDataPageableTest()
//        {
//            PagedResult<TestGroup> expectedResult;

//            _repository
//                 .Setup(it => it.GetDataPageable(It.IsAny<String>(), It.IsAny<Int32>(), It.IsAny<Int32>()))
//                 .Returns<String, Int32, Int32>((sortExpression, page, pageSize) => 
//                 { 
//                      var query = _repositoryList;
//                      switch (sortExpression)
//                      {
//                          case  "Id":
//                              query = new List<TestGroup>(query.OrderBy(q => q.Id));
//                              break;
//                          case  "ProjectId":
//                              query = new List<TestGroup>(query.OrderBy(q => q.ProjectId));
//                              break;
//                          case  "Name":
//                              query = new List<TestGroup>(query.OrderBy(q => q.Name));
//                              break;
//                          case  "IsActive":
//                              query = new List<TestGroup>(query.OrderBy(q => q.IsActive));
//                              break;                      }
//                      return query.Take(pageSize).Skip((page-1)*pageSize).ToList();
//                 });

//            _repository
//                 .Setup(it => it.GetRowCount())
//                 .Returns(_repositoryList.Count);

//            var result = _target.GetDataPageable("Id", 1, 2);
//            Assert.IsTrue(result.TryGetContentValue(out expectedResult));
//            Assert.AreEqual(_repositoryList.Take(2).ToList().Count, expectedResult.Results.Count);
//            Assert.AreEqual(_repositoryList.OrderBy(q => q.Id).FirstOrDefault().Id, expectedResult.Results.FirstOrDefault().Id);
//        }

//        [Test()]
//        public void GetDataByIdTest() 
//        {
//            _repository
//                 .Setup(it => it.GetDataById(It.IsAny<Int32>()))
//                     .Returns<Int32>((id) => 
//                 { 
//                      return _repositoryList.Where(x => x.Id==id).ToList();
//                 });
                
//            var result = _target.GetDataById(idValue).ToList();
//             Assert.AreEqual(_repositoryList.Where(x => x.Id==idValue).ToList().Count, result.Count);
//        }

//        [Test()]
//        public void GetActiveDataTest() 
//        {
//            _repository
//                 .Setup(it => it.GetActiveData())
//                     .Returns(_repositoryList);
                
//            var result = _target.GetActiveData().ToList();
//             Assert.AreEqual(_repositoryList.ToList().Count, result.Count);
//        }

//        [Test()]
//        public void GetActiveDataPageableTest()
//        {
//            PagedResult<TestGroup> expectedResult;

//            _repository
//                 .Setup(it => it.GetActiveDataPageable(It.IsAny<String>(), It.IsAny<Int32>(), It.IsAny<Int32>()))
//                 .Returns<String, Int32, Int32>((sortExpression, page, pageSize) => 
//                 { 
//                      var query = _repositoryList;
//                      switch (sortExpression)
//                      {
//                          case  "Id":
//                              query = new List<TestGroup>(query.OrderBy(q => q.Id));
//                              break;
//                          case  "ProjectId":
//                              query = new List<TestGroup>(query.OrderBy(q => q.ProjectId));
//                              break;
//                          case  "Name":
//                              query = new List<TestGroup>(query.OrderBy(q => q.Name));
//                              break;
//                          case  "IsActive":
//                              query = new List<TestGroup>(query.OrderBy(q => q.IsActive));
//                              break;                      }
//                      return query.Take(pageSize).Skip((page-1)*pageSize).ToList();
//                 });

//            _repository
//                 .Setup(it => it.GetActiveDataRowCount())
//                 .Returns(_repositoryList.Count);

//            var result = _target.GetActiveDataPageable("Id", 1, PageSizeValue);
//            Assert.IsTrue(result.TryGetContentValue(out expectedResult));
//            Assert.AreEqual(_repositoryList.Take(2).ToList().Count, expectedResult.Results.Count);
//            Assert.AreEqual(_repositoryList.OrderBy(q => q.Id).FirstOrDefault().Id, expectedResult.Results.FirstOrDefault().Id);
//        }

//        [Test()]
//        public void GetDataByProjectIdTest() 
//        {
//            _repository
//                 .Setup(it => it.GetDataByProjectId(It.IsAny<Int32>()))
//                     .Returns<Int32>((projectId) => 
//                 { 
//                      return _repositoryList.Where(x => x.ProjectId==projectId).ToList();
//                 });
                
//            var result = _target.GetDataByProjectId(projectIdValue).ToList();
//             Assert.AreEqual(_repositoryList.Where(x => x.ProjectId==projectIdValue).ToList().Count, result.Count);
//        }

//        [Test()]
//        public void GetDataByProjectIdPageableTest()
//        {
//            PagedResult<TestGroup> expectedResult;

//            _repository
//                 .Setup(it => it.GetDataByProjectIdPageable(It.IsAny<Int32>(), It.IsAny<String>(), It.IsAny<Int32>(), It.IsAny<Int32>()))
//                 .Returns<Int32, String, Int32, Int32>((projectId, sortExpression, page, pageSize) => 
//                 { 
//                      var query = _repositoryList.Where(x => x.ProjectId==projectId);
//                      switch (sortExpression)
//                      {
//                          case  "Id":
//                              query = new List<TestGroup>(query.OrderBy(q => q.Id));
//                              break;
//                          case  "ProjectId":
//                              query = new List<TestGroup>(query.OrderBy(q => q.ProjectId));
//                              break;
//                          case  "Name":
//                              query = new List<TestGroup>(query.OrderBy(q => q.Name));
//                              break;
//                          case  "IsActive":
//                              query = new List<TestGroup>(query.OrderBy(q => q.IsActive));
//                              break;                      }
//                      return query.Take(pageSize).Skip((page-1)*pageSize).ToList();
//                 });

//            _repository
//                 .Setup(it => it.GetDataByProjectIdRowCount(projectId))
//                 .Returns(_repositoryList.Count);

//            var result = _target.GetDataByProjectIdPageable(ProjectIdValue, "Id", 1, 2);
//            Assert.IsTrue(result.TryGetContentValue(out expectedResult));
//            Assert.AreEqual(_repositoryList.Where(x => x.ProjectId==projectId).Take(2).ToList().Count, expectedResult.Results.Count);
//            Assert.AreEqual(_repositoryList.Where(x => x.ProjectId==projectId).OrderBy(q => q.Id).FirstOrDefault().Id, expectedResult.Results.FirstOrDefault().Id);
//        }

//        [Test()]
//        public void GetActiveDataByProjectIdTest() 
//        {
//            _repository
//                 .Setup(it => it.GetActiveDataByProjectId(It.IsAny<Int32>()))
//                     .Returns<Int32>((projectId) => 
//                 { 
//                      return _repositoryList.Where(x => x.ProjectId==projectId).ToList();
//                 });
                
//            var result = _target.GetActiveDataByProjectId(projectIdValue).ToList();
//             Assert.AreEqual(_repositoryList.Where(x => x.ProjectId==projectIdValue).ToList().Count, result.Count);
//        }

//        [Test()]
//        public void GetActiveDataByProjectIdPageableTest()
//        {
//            PagedResult<TestGroup> expectedResult;

//            _repository
//                 .Setup(it => it.GetActiveDataByProjectIdPageable(It.IsAny<Int32>(), It.IsAny<String>(), It.IsAny<Int32>(), It.IsAny<Int32>()))
//                 .Returns<Int32, String, Int32, Int32>((projectId, sortExpression, page, pageSize) => 
//                 { 
//                      var query = _repositoryList;
//                      switch (sortExpression)
//                      {
//                          case  "Id":
//                              query = new List<TestGroup>(query.OrderBy(q => q.Id));
//                              break;
//                          case  "ProjectId":
//                              query = new List<TestGroup>(query.OrderBy(q => q.ProjectId));
//                              break;
//                          case  "Name":
//                              query = new List<TestGroup>(query.OrderBy(q => q.Name));
//                              break;
//                          case  "IsActive":
//                              query = new List<TestGroup>(query.OrderBy(q => q.IsActive));
//                              break;                      }
//                      return query.Take(pageSize).Skip((page-1)*pageSize).ToList();
//                 });

//            _repository
//                 .Setup(it => it.GetActiveDataByProjectIdRowCount(projectId))
//                 .Returns(_repositoryList.Count);

//            var result = _target.GetActiveDataByProjectIdPageable(ProjectIdValue, "Id", 1, PageSizeValue);
//            Assert.IsTrue(result.TryGetContentValue(out expectedResult));
//            Assert.AreEqual(_repositoryList.Take(2).ToList().Count, expectedResult.Results.Count);
//            Assert.AreEqual(_repositoryList.OrderBy(q => q.Id).FirstOrDefault().Id, expectedResult.Results.FirstOrDefault().Id);
//        }


//    }
//}
