//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
(function() {
    "use strict";

    var controllerId = "scriptIndexCtrl";
    angular.module("app").controller(controllerId, ["common", "scriptDataService", scriptIndexCtrl]);

    function scriptIndexCtrl(common, scriptDataService) {
        var getLogFn = common.logger.getLogFn;
        var log = getLogFn(controllerId);

        var vm = this;
        vm.news = {
            title: "Script List",
            description: "Script List"
        };

        vm.pageableResults = [];
        vm.title = "ScriptList";
        vm.sortExpression = "";
        vm.currentPage = 1;
        vm.pageSize = 10;
        vm.deleteScript = deleteScript;

        activate();

        vm.pageChanged = function() {
            return getDataPageable(vm.sortExpression, vm.currentPage, vm.pageSize);
        };

        function activate() {
            var promises = [getDataPageable(vm.sortExpression, vm.currentPage, vm.pageSize)];
            common.activateController(promises, controllerId)
                .then(function() { log("Activated Script List View"); });
        }

        function getDataPageable(sortExpression, page, pageSize) {
            return scriptDataService.getDataPageable(sortExpression, page, pageSize).then(function(results) {
                return vm.pageableResults = results.data;
            });
        }

        function deleteScript(scriptId) {
            alert("test worked");
            //  return scriptDataService.deleteScript(scriptId);
        };
    }
})();