'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Data

Namespace LucentDb.Data.DbCommandProvider
    Public Interface IDbScript_ExpectedResultCommandProvider
        ReadOnly Property Script_ExpectedResultDbConnectionHolder() As DbConnectionHolder
        ReadOnly Property DbConnectionName As String
        Function GetGetDataDbCommand() As IDbCommand
        Function GetUpdateDbCommand( ByVal scriptId As Int32,  ByVal expectedResultId As Int32,  ByVal resultIndex As Int32,  ByVal original_ScriptId As Int32,  ByVal original_ExpectedResultId As Int32) As IDbCommand
        Function GetDeleteDbCommand( ByVal scriptId As Int32,  ByVal expectedResultId As Int32) As IDbCommand
        Function GetInsertDbCommand( ByVal scriptId As Int32,  ByVal expectedResultId As Int32,  ByVal resultIndex As Int32) As IDbCommand
        Function GetGetDataPageableDbCommand( ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32) As IDbCommand
        Function GetGetRowCountDbCommand() As IDbCommand
        Function GetGetDataByScriptIdExpectedResultIdDbCommand( ByVal scriptId As Int32,  ByVal expectedResultId As Int32) As IDbCommand
        Function GetGetDataByExpectedResultIdDbCommand( ByVal expectedResultId As Int32) As IDbCommand
        Function GetGetDataByExpectedResultIdPageableDbCommand( ByVal expectedResultId As Int32,  ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32) As IDbCommand
        Function GetGetDataByExpectedResultIdRowCountDbCommand( ByVal expectedResultId As Int32) As IDbCommand
        Function GetGetDataByScriptIdDbCommand( ByVal scriptId As Int32) As IDbCommand
        Function GetGetDataByScriptIdPageableDbCommand( ByVal scriptId As Int32,  ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32) As IDbCommand
        Function GetGetDataByScriptIdRowCountDbCommand( ByVal scriptId As Int32) As IDbCommand

    End Interface
End Namespace
