'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports LucentDb.Domain.Entities


Namespace LucentDb.Data.Repository
    Public Interface IConnectionRepository
        Function GetData() As ICollection(Of Connection)
        Sub Update(name As String, connectionString As String, isActive As Boolean, id As Int32)
        Sub Update(connection As Connection)
        Sub Delete(id As Int32)
        Sub Delete(connection As Connection)
        Function Insert(name As String, connectionString As String, isActive As Boolean) As Int32
        Function Insert(connection As Connection) As Int32

        Function GetDataPageable(sortExpression As String, page As Int32, pageSize As Int32) _
            As ICollection(Of Connection)

        Function GetRowCount() As Int32
        Function GetDataById(id As Int32) As ICollection(Of Connection)
        Function GetActiveData() As ICollection(Of Connection)

        Function GetActiveDataPageable(sortExpression As String, page As Int32, pageSize As Int32) _
            As ICollection(Of Connection)

        Function GetActiveDataRowCount() As Int32
        Function GetConnectionsByProjectId(projectId As Int32) As ICollection(Of Connection)
    End Interface
End Namespace
