'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports LucentDb.Domain.Entities


Namespace LucentDb.Data.Repository
    Public Interface IExpectedResultTypeRepository
        Function GetData() as ICollection(Of ExpectedResultType)
        Sub Update(name As String, id As Int32)
        Sub Update(expectedResultType as ExpectedResultType)
        Sub Delete(id As Int32)
        Sub Delete(expectedResultType as ExpectedResultType)
        Function Insert(name As String) as Int32
        Function Insert(expectedResultType as ExpectedResultType) as Int32

        Function GetDataPageable(sortExpression As String, page As Int32, pageSize As Int32) _
            As PagedResult(Of ExpectedResultType)

        Function GetDataById(id As Int32) as ICollection(Of ExpectedResultType)
    End Interface
End NameSpace
