'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports LucentDb.Domain.Entities


Namespace LucentDb.Data.Repository
    Public Interface IProjectRepository
        Function GetData() as ICollection(Of Project)
        Sub Update(name As String, isActive As Boolean, projectId As Int32)
        Sub Update(project as Project)
        Sub Delete(projectId As Int32)
        Sub Delete(project as Project)
        Function Insert(name As String, isActive As Boolean) as Int32
        Function Insert(project as Project) as Int32
        Function GetDataPageable(sortExpression As String, page As Int32, pageSize As Int32) as ICollection(Of Project)
        Function GetRowCount() as Int32
        Function GetDataByProjectId(projectId As Int32) as ICollection(Of Project)
        Function GetActiveData() as ICollection(Of Project)

        Function GetActiveDataPageable(sortExpression As String, page As Int32, pageSize As Int32) _
            as ICollection(Of Project)

        Function GetActiveDataRowCount() as Int32
        Function GetProjectsForConnectionByConnectionId(connectionId As Int32) as ICollection(Of Project)

        Function GetProjectsForConnectionByConnectionIdPageable(connectionId As Int32, sortExpression As String,
                                                                page As Int32, pageSize As Int32) _
            as ICollection(Of Project)

        Function GetProjectsForConnectionByConnectionIdRowCount(connectionId As Int32) as Int32
    End Interface
End NameSpace
