'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports LucentDb.Data
Imports LucentDb.Domain.Entities

  
 Namespace LucentDb.Data.Repository     
    Public Interface IRunHistoryRepository
        Function GetData()  as ICollection(Of RunHistory)
        Sub Update( ByVal testId As  Nullable(Of Int32) ,  ByVal projectId As  Nullable(Of Int32) ,  ByVal testGroupId As  Nullable(Of Int32) ,  ByVal runDateTime As DateTime,  ByVal isValid As Boolean,  ByVal runLog As String,  ByVal id As Int64) 
        Sub Update(ByVal runHistory as RunHistory) 
        Sub Delete( ByVal id As Int64) 
        Sub Delete(ByVal runHistory as RunHistory) 
        Function Insert( ByVal testId As  Nullable(Of Int32) ,  ByVal projectId As  Nullable(Of Int32) ,  ByVal testGroupId As  Nullable(Of Int32) ,  ByVal runDateTime As DateTime,  ByVal isValid As Boolean,  ByVal runLog As String)  as Int64
        Function Insert(ByVal runHistory as RunHistory)  as Int64
        Function GetDataPageable( ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as PagedResult(Of RunHistory)
        Function GetDataById( ByVal id As Int64)  as ICollection(Of RunHistory)
        Function GetDataByTestId( ByVal testId As Int32)  as ICollection(Of RunHistory)
        Function GetDataByTestIdPageable( ByVal testId As Int32,  ByVal sortExpression As String,  ByVal page As Int32,  ByVal pageSize As Int32)  as PagedResult(Of RunHistory)
    End Interface 
End NameSpace
  