'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports LucentDb.Domain.Entities


Namespace LucentDb.Data.Repository
    Public Interface IRunHistoryRepository
        Function GetData() As ICollection(Of RunHistory)

        Sub Update(testId As Nullable(Of Int32), projectId As Nullable(Of Int32), groupId As Nullable(Of Int32),
                   connectionId As Nullable(Of Int32), runDateTime As DateTime, totalDuration As Nullable(Of Decimal),
                   isValid As Boolean, runLog As String, id As Int64)

        Sub Update(runHistory As RunHistory)
        Sub Delete(id As Int64)
        Sub Delete(runHistory As RunHistory)

        Function Insert(testId As Nullable(Of Int32), projectId As Nullable(Of Int32), groupId As Nullable(Of Int32),
                        connectionId As Nullable(Of Int32), runDateTime As DateTime,
                        totalDuration As Nullable(Of Decimal), isValid As Boolean, runLog As String) As Int64

        Function Insert(runHistory As RunHistory) As Int64

        Function GetDataPageable(sortExpression As String, page As Int32, pageSize As Int32) _
            As PagedResult(Of RunHistory)

        Function GetDataById(id As Int64) As ICollection(Of RunHistory)
        Function GetDataByProjectId(projectId As Int32) As ICollection(Of RunHistory)

        Function GetDataByProjectIdPageable(projectId As Int32, sortExpression As String, page As Int32,
                                            pageSize As Int32) As PagedResult(Of RunHistory)

        Function GetDataByTestId(testId As Int32) As ICollection(Of RunHistory)

        Function GetDataByTestIdPageable(testId As Int32, sortExpression As String, page As Int32, pageSize As Int32) _
            As PagedResult(Of RunHistory)

        Function GetDataByGroupId(groupId As Int32) As ICollection(Of RunHistory)

        Function GetDataByGroupIdPageable(groupId As Int32, sortExpression As String, page As Int32, pageSize As Int32) _
            As PagedResult(Of RunHistory)
    End Interface
End Namespace
