'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports LucentDb.Domain.Entities


Namespace LucentDb.Data.Repository
    Public Interface IScript_ExpectedResultRepository
        Function GetData() as ICollection(Of Script_ExpectedResult)

        Sub Update(scriptId As Int32, expectedResultId As Int32, resultIndex As Int32, original_ScriptId As Int32,
                   original_ExpectedResultId As Int32)

        Sub Update(script_ExpectedResult as Script_ExpectedResult, original_ScriptId As Int32,
                   original_ExpectedResultId As Int32)

        Sub Delete(scriptId As Int32, expectedResultId As Int32)
        Sub Delete(script_ExpectedResult as Script_ExpectedResult)

        Function Insert(scriptId As Int32, expectedResultId As Int32, resultIndex As Int32) _
            as ICollection(Of Script_ExpectedResult)

        Function Insert(script_ExpectedResult as Script_ExpectedResult) as ICollection(Of Script_ExpectedResult)

        Function GetDataPageable(sortExpression As String, page As Int32, pageSize As Int32) _
            as ICollection(Of Script_ExpectedResult)

        Function GetRowCount() as Int32

        Function GetDataByScriptIdExpectedResultId(scriptId As Int32, expectedResultId As Int32) _
            as ICollection(Of Script_ExpectedResult)

        Function GetDataByExpectedResultId(expectedResultId As Int32) as ICollection(Of Script_ExpectedResult)

        Function GetDataByExpectedResultIdPageable(expectedResultId As Int32, sortExpression As String, page As Int32,
                                                   pageSize As Int32) as ICollection(Of Script_ExpectedResult)

        Function GetDataByExpectedResultIdRowCount(expectedResultId As Int32) as Int32
        Function GetDataByScriptId(scriptId As Int32) as ICollection(Of Script_ExpectedResult)

        Function GetDataByScriptIdPageable(scriptId As Int32, sortExpression As String, page As Int32, pageSize As Int32) _
            as ICollection(Of Script_ExpectedResult)

        Function GetDataByScriptIdRowCount(scriptId As Int32) as Int32
    End Interface
End NameSpace
