'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports LucentDb.Domain.Entities


Namespace LucentDb.Data.Repository
    Public Interface IScriptTypeRepository
        Function GetData() As ICollection(Of ScriptType)
        Sub Update(name As String, isActive As Boolean, id As Int32)
        Sub Update(scriptType As ScriptType)
        Sub Delete(id As Int32)
        Sub Delete(scriptType As ScriptType)
        Function Insert(name As String, isActive As Boolean) As Int32
        Function Insert(scriptType As ScriptType) As Int32

        Function GetDataPageable(sortExpression As String, page As Int32, pageSize As Int32) _
            As ICollection(Of ScriptType)

        Function GetRowCount() As Int32
        Function GetDataById(id As Int32) As ICollection(Of ScriptType)
        Function GetActiveData() As ICollection(Of ScriptType)

        Function GetActiveDataPageable(sortExpression As String, page As Int32, pageSize As Int32) _
            As ICollection(Of ScriptType)

        Function GetActiveDataRowCount() As Int32
    End Interface
End Namespace
