'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports LucentDb.Domain.Entities


Namespace LucentDb.Data.Repository
    Public Interface ITestGroupRepository
        Function GetData() as ICollection(Of TestGroup)
        Sub Update(projectId As Int32, name As String, isActive As Boolean, id As Int32)
        Sub Update(testGroup as TestGroup)
        Sub Delete(id As Int32)
        Sub Delete(testGroup as TestGroup)
        Function Insert(projectId As Int32, name As String, isActive As Boolean) as Int32
        Function Insert(testGroup as TestGroup) as Int32

        Function GetDataPageable(sortExpression As String, page As Int32, pageSize As Int32) _
            as PagedResult(Of TestGroup)

        Function GetDataById(id As Int32) as ICollection(Of TestGroup)
        Function GetActiveData() as ICollection(Of TestGroup)

        Function GetActiveDataPageable(sortExpression As String, page As Int32, pageSize As Int32) _
            as PagedResult(Of TestGroup)

        Function GetDataByProjectId(projectId As Int32) as ICollection(Of TestGroup)

        Function GetDataByProjectIdPageable(projectId As Int32, sortExpression As String, page As Int32,
                                            pageSize As Int32) as PagedResult(Of TestGroup)

        Function GetActiveDataByProjectId(projectId As Int32) as ICollection(Of TestGroup)

        Function GetActiveDataByProjectIdPageable(projectId As Int32, sortExpression As String, page As Int32,
                                                  pageSize As Int32) as PagedResult(Of TestGroup)
    End Interface
End NameSpace
