//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Web.Mvc;
using LucentDb.Data.Repository;
using LucentDb.Domain.Entities;

namespace LucentDb.Web.UI.Controllers
{
    public class ProjectController : Controller
    {
        private readonly IProjectRepository _dbProjectRepository;
        

        public ProjectController(IProjectRepository dbProjectRepository)
        {
            _dbProjectRepository = dbProjectRepository;
            
        }
        
        // GET: Project
        public ActionResult Index()
        {
            return View();
        }

        // GET: Project/Details/5
        [Route("Project/Details/{projectId}", Name = "GetProjectDetails")]
        public ActionResult Details(Int32 projectId)
        {
            return View(_dbProjectRepository.GetDataByProjectId(projectId).FirstOrDefault());
        }

        // GET: Project/Create
        public ActionResult Create()
        {
            
            return View();
        }

        // POST: Project/Create
        [HttpPost]
        public ActionResult Create(Project project)
        {
            try
            {
                _dbProjectRepository.Insert(project);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(project);
            }
        }

        // GET: Project/Edit/5
        [Route("Project/Edit/{projectId}", Name = "GetProjectEdit")]
        public ActionResult Edit(Int32 projectId)
        {
        	var project = _dbProjectRepository.GetDataByProjectId(projectId).FirstOrDefault();    
            
            return View(project);
        }

        // POST: Project/Edit/5
        [Route("Project/Edit/{projectId}", Name = "PostProjectEdit")]
        [HttpPost]
        public ActionResult Edit(Int32 projectId, Project project)
        {
            try
            {
                _dbProjectRepository.Update(project);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(project);
            }
        }
   }
}
