//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Web.Mvc;
using LucentDb.Data.Repository;
using LucentDb.Domain.Entities;

namespace LucentDb.Web.UI.Controllers
{
    public class TestController : Controller
    {
        private readonly ITestRepository _dbTestRepository;
        private readonly IProjectRepository _dbProjectRepository;
        private readonly ITestTypeRepository _dbTestTypeRepository;
        

        public TestController(ITestRepository dbTestRepository, IProjectRepository dbProjectRepository, ITestTypeRepository dbTestTypeRepository)
        {
            _dbTestRepository = dbTestRepository;
            _dbProjectRepository = dbProjectRepository; 
            _dbTestTypeRepository = dbTestTypeRepository; 
            
        }
        
        // GET: Test
        public ActionResult Index()
        {
            return View();
        }

        // GET: Test/Details/5
        [Route("Test/Details/{id}", Name = "GetTestDetails")]
        public ActionResult Details(Int32 id)
        {
            return View(_dbTestRepository.GetDataById(id).FirstOrDefault());
        }

        // GET: Test/Create
        public ActionResult Create()
        {
            ViewBag.Projects = new SelectList(_dbProjectRepository.GetData(), "ProjectId", "ProjectId");
            ViewBag.TestTypes = new SelectList(_dbTestTypeRepository.GetData(), "Id", "Id");
            
            return View();
        }

        // POST: Test/Create
        [HttpPost]
        public ActionResult Create(Test test)
        {
            try
            {
                _dbTestRepository.Insert(test);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(test);
            }
        }

        // GET: Test/Edit/5
        [Route("Test/Edit/{id}", Name = "GetTestEdit")]
        public ActionResult Edit(Int32 id)
        {
        	var test = _dbTestRepository.GetDataById(id).FirstOrDefault();    
            if (test != null) ViewBag.Projects = new SelectList(_dbProjectRepository.GetData(), "ProjectId", "ProjectId", test.ProjectId);
            if (test != null) ViewBag.TestTypes = new SelectList(_dbTestTypeRepository.GetData(), "Id", "Id", test.TestTypeId);
            
            return View(test);
        }

        // POST: Test/Edit/5
        [Route("Test/Edit/{id}", Name = "PostTestEdit")]
        [HttpPost]
        public ActionResult Edit(Int32 id, Test test)
        {
            try
            {
                _dbTestRepository.Update(test);
                return RedirectToAction("Index");
            }
            catch
            {
                return View(test);
            }
        }
   }
}
