//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
(function () {
    'use strict';

    var serviceId = 'assertTypeDataService';
    angular.module('app').service(serviceId, ['$http', assertTypeDataService]);

    function assertTypeDataService($http) {
        var urlBase = '/api/assertTypes';            

        this.getData = function () {
            return $http.get('/api/assertTypes'/all');
        };

         this.updateAssertType = function(assertType) {
            return $http.put('/api/assertTypes'', assertType);
        };

         this.deleteAssertType = function(id) {
            return $http.Delete('/api/assertTypes'', id);
        };

         this.insertAssertType = function(assertType) {
            return $http.post('/api/assertTypes'', assertType);
        };

        this.getDataPageable = function (sortExpression, page, pageSize) { 
            return $http({
                 url: '/api/assertTypes'',
                 method: 'GET',
                 params: {
                     sortExpression : sortExpression || '', 
                     page : page || '', 
                     pageSize : pageSize || ''
                 }
            });
        };

        this.getDataById = function (id) {
            return $http.get('/api/assertTypes/' + id + '/assertTypes');
        };


    }
})();
