//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
(function() {
    "use strict";

    var serviceId = "testTypeDataService";
    angular.module("app").service(serviceId, ["$http", testTypeDataService]);

    function testTypeDataService($http) {
        var urlBase = "/api/testTypes";

        this.getData = function() {
            return $http.get(urlBase + "/all");
        };

        this.updateTestType = function(testType) {
            return $http.put(urlBase, testType);
        };

        this.deleteTestType = function(id) {
            return $http.Delete(urlBase, id);
        };

        this.insertTestType = function(testType) {
            return $http.post(urlBase, testType);
        };

        this.getDataPageable = function(sortExpression, page, pageSize) {
            return $http({
                url: urlBase,
                method: "GET",
                params: {
                    sortExpression: sortExpression || "",
                    page: page || "",
                    pageSize: pageSize || ""
                }
            });
        };

        this.getDataById = function(id) {
            return $http.get("/api/expectedResults/" + assertTypeId + "/testTypes/all");
        };

        this.getActiveData = function() {
            return $http.get(urlBase + "/all");
        };

        this.getActiveDataPageable = function(sortExpression, page, pageSize) {
            return $http({
                url: urlBase,
                method: "GET",
                params: {
                    sortExpression: sortExpression || "",
                    page: page || "",
                    pageSize: pageSize || ""
                }
            });
        };


    }
})();