//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;

namespace LucentDb.Domain.Entities
{
    [Serializable]
    public class RunHistoryList : Collection<RunHistory>
    {
        public RunHistory First()
        {
            return Count > 0 ? base[0] : null;
        }
    }

    [DataContract]
    public class RunHistory
    {
        private long _id;
        private bool _isPass;
        private string _resultString;
        private DateTime _runDateTime;
        private int _scriptId;

        public RunHistory()
        {
        }

        public RunHistory(long id, int scriptId, DateTime runDateTime, bool isPass, string resultString)
        {
            _id = id;
            _scriptId = scriptId;
            _runDateTime = runDateTime;
            _isPass = isPass;
            _resultString = resultString;
        }

        /// <summary>
        ///     Public Property Id
        /// </summary>
        /// <returns>Id as Int64</returns>
        /// <remarks></remarks>
        [DataMember]
        public virtual long Id
        {
            get { return _id; }
            set { _id = value; }
        }

        /// <summary>
        ///     Public Property ScriptId
        /// </summary>
        /// <returns>ScriptId as Int32</returns>
        /// <remarks></remarks>
        [DataMember]
        public virtual int ScriptId
        {
            get { return _scriptId; }
            set { _scriptId = value; }
        }

        /// <summary>
        ///     Public Property RunDateTime
        /// </summary>
        /// <returns>RunDateTime as DateTime</returns>
        /// <remarks></remarks>
        [DataMember]
        public virtual DateTime RunDateTime
        {
            get { return _runDateTime; }
            set { _runDateTime = value; }
        }

        /// <summary>
        ///     Public Property IsPass
        /// </summary>
        /// <returns>IsPass as Boolean</returns>
        /// <remarks></remarks>
        [DataMember]
        public virtual bool IsPass
        {
            get { return _isPass; }
            set { _isPass = value; }
        }

        /// <summary>
        ///     Public Property ResultString
        /// </summary>
        /// <returns>ResultString as String</returns>
        /// <remarks></remarks>
        [DataMember]
        public virtual string ResultString
        {
            get { return _resultString; }
            set { _resultString = value; }
        }

        [DataMember]
        public virtual Script ScriptScript { get; set; }
    }
}