//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;

namespace LucentDb.Domain.Entities
{
    [Serializable]
    public class RunHistoryDetailList : Collection<RunHistoryDetail>
    {
        public RunHistoryDetail First()
        {
            return Count > 0 ? base[0] : null;
        }
    }

    [DataContract]
    public class RunHistoryDetail
    {
        private decimal? _duration;
        private long _id;
        private bool _isValid;
        private string _resultString;
        private DateTime _runDateTime;
        private long _runHistoryId;
        private int _testId;

        public RunHistoryDetail()
        {
        }

        public RunHistoryDetail(long id, long runHistoryId, int testId, DateTime runDateTime, decimal? duration,
            bool isValid, string resultString)
        {
            _id = id;
            _runHistoryId = runHistoryId;
            _testId = testId;
            _runDateTime = runDateTime;
            _duration = duration;
            _isValid = isValid;
            _resultString = resultString;
        }

        /// <summary>
        ///     Public Property Id
        /// </summary>
        /// <returns>Id as Int64</returns>
        /// <remarks></remarks>
        [DataMember]
        public virtual long Id
        {
            get { return _id; }
            set { _id = value; }
        }

        /// <summary>
        ///     Public Property RunHistoryId
        /// </summary>
        /// <returns>RunHistoryId as Int64</returns>
        /// <remarks></remarks>
        [DataMember]
        public virtual long RunHistoryId
        {
            get { return _runHistoryId; }
            set { _runHistoryId = value; }
        }

        /// <summary>
        ///     Public Property TestId
        /// </summary>
        /// <returns>TestId as Int32</returns>
        /// <remarks></remarks>
        [DataMember]
        public virtual int TestId
        {
            get { return _testId; }
            set { _testId = value; }
        }

        /// <summary>
        ///     Public Property RunDateTime
        /// </summary>
        /// <returns>RunDateTime as DateTime</returns>
        /// <remarks></remarks>
        [DataMember]
        public virtual DateTime RunDateTime
        {
            get { return _runDateTime; }
            set { _runDateTime = value; }
        }

        /// <summary>
        ///     Public Property Duration
        /// </summary>
        /// <returns>Duration as Nullable<Decimal></returns>
        /// <remarks></remarks>
        [DataMember]
        public virtual decimal? Duration
        {
            get { return _duration; }
            set { _duration = value; }
        }

        /// <summary>
        ///     Public Property IsValid
        /// </summary>
        /// <returns>IsValid as Boolean</returns>
        /// <remarks></remarks>
        [DataMember]
        public virtual bool IsValid
        {
            get { return _isValid; }
            set { _isValid = value; }
        }

        /// <summary>
        ///     Public Property ResultString
        /// </summary>
        /// <returns>ResultString as String</returns>
        /// <remarks></remarks>
        [DataMember]
        public virtual string ResultString
        {
            get { return _resultString; }
            set { _resultString = value; }
        }

        [DataMember]
        public virtual RunHistory RunHistory { get; set; }
    }
}