//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;


namespace LucentDb.Domain.Entities
{
    [Serializable]
    public partial class TestList :  Collection<Test>
    {
        public Test First()
        {
          return base.Count > 0 ? base[0] : null;
        }
    }
    
    [DataContract]
    public partial class Test{
      
        private Int32 _id;
        private Int32 _projectId;
        private Int32 _testTypeId;
        private String _name;
        private Boolean _isActive;
        private Collection<Script> _scripts; 
        private Project _project; 
        private TestType _testType;  

      public Test() : base()
      {
      }

      public Test(Int32 id, Int32 projectId, Int32 testTypeId, String name, Boolean isActive) : base()
      {
          
           _id = id;
           _projectId = projectId;
           _testTypeId = testTypeId;
           _name = name;
           _isActive = isActive;
      }
  
    
        /// <summary>
        /// Public Property Id
        /// </summary>
        /// <returns>Id as Int32</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Int32 Id
        {
            get{return this._id;}
            set{this._id = value;}
        }

        /// <summary>
        /// Public Property ProjectId
        /// </summary>
        /// <returns>ProjectId as Int32</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Int32 ProjectId
        {
            get{return this._projectId;}
            set{this._projectId = value;}
        }

        /// <summary>
        /// Public Property TestTypeId
        /// </summary>
        /// <returns>TestTypeId as Int32</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Int32 TestTypeId
        {
            get{return this._testTypeId;}
            set{this._testTypeId = value;}
        }

        /// <summary>
        /// Public Property Name
        /// </summary>
        /// <returns>Name as String</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual String Name
        {
            get{return this._name;}
            set{this._name = value;}
        }

        /// <summary>
        /// Public Property IsActive
        /// </summary>
        /// <returns>IsActive as Boolean</returns>
        /// <remarks></remarks>
        [DataMember()]
        public virtual Boolean IsActive
        {
            get{return this._isActive;}
            set{this._isActive = value;}
        }

        [DataMember]
        public virtual Collection<Script> Scripts 
        {
          get { return  _scripts;}
          set { _scripts = value;}
        }
  
      
        [DataMember]
        public virtual Project Project 
        {
          get { return  _project;}
          set { _project = value;}
        }
  
      
        [DataMember]
        public virtual TestType TestType 
        {
          get { return  _testType;}
          set { _testType = value;}
        }
  
      
    }
 }     
