//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//-----------------------------------------------------------------------------
using LucentDb.Data.Repository;
using System.Linq;
  
namespace LucentDb.Domain.Entities.Extensions 
{
  public static class Project_ConnectionExtensions
  {
   
     
      public static Project_Connection IncludeConnectionConnection(this Project_Connection project_Connection, IConnectionRepository connectionRepository) 
      {
         if (project_Connection.ConnectionConnection != null) return  project_Connection;   
               project_Connection.ConnectionConnection = connectionRepository.GetDataById(project_Connection.ConnectionId).ToList().First();
         return  project_Connection;      
      }
  
     
      public static Project_Connection IncludeProjectProject(this Project_Connection project_Connection, IProjectRepository projectRepository) 
      {
         if (project_Connection.ProjectProject != null) return  project_Connection;   
               project_Connection.ProjectProject = projectRepository.GetDataById(project_Connection.ProjectId).ToList().First();
         return  project_Connection;      
      }
     
  }    
}    
