//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//-----------------------------------------------------------------------------
using LucentDb.Data.Repository;
using System.Linq;
  
namespace LucentDb.Domain.Entities.Extensions 
{
  public static class RunHistoryExtensions
  {
   
     
      public static RunHistory IncludeTest(this RunHistory runHistory, ITestRepository testRepository) 
      {
         if (runHistory.Test != null) return  runHistory;   
               runHistory.Test = testRepository.GetDataById(runHistory.TestId).ToList().First();
         return  runHistory;      
      }
     
  }    
}    
