//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//-----------------------------------------------------------------------------
using LucentDb.Data.Repository;
using System.Linq;
  
namespace LucentDb.Domain.Entities.Extensions 
{
  public static class ScriptTypeExtensions
  {
   
     
      public static ScriptType IncludeScripts(this ScriptType scriptType, IScriptRepository scriptRepository) 
      {
         if (scriptType.Scripts != null) return  scriptType;   
               scriptType.Scripts = (ScriptList)scriptRepository.GetDataByScriptTypeId(scriptType.Id);
         return  scriptType;      
      }
     
  }    
}    
