//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//-----------------------------------------------------------------------------
using LucentDb.Data.Repository;
using System.Linq;
  
namespace LucentDb.Domain.Entities.Extensions 
{
  public static class TestValueTypeExtensions
  {
   
     
      public static TestValueType IncludeTests(this TestValueType testValueType, ITestRepository testRepository) 
      {
         if (testValueType.Tests != null) return  testValueType;   
               testValueType.Tests = (TestList)testRepository.GetDataByTestValueTypeId(testValueType.Id);
         return  testValueType;      
      }
  
     
      public static TestValueType IncludeTestType(this TestValueType testValueType, ITestTypeRepository testTypeRepository) 
      {
         if (testValueType.TestType != null) return  testValueType;   
               testValueType.TestType = testTypeRepository.GetDataById(testValueType.TestTypeId).ToList().First();
         return  testValueType;      
      }
     
  }    
}    
