//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//-----------------------------------------------------------------------------
using LucentDb.Data.Repository;
using System.Linq;
  
namespace LucentDb.Domain.Entities.Extensions 
{
  public static class Test_ScriptExtensions
  {
   
     
      public static Test_Script IncludeScriptScript(this Test_Script test_Script, IScriptRepository scriptRepository) 
      {
         if (test_Script.ScriptScript != null) return  test_Script;   
               test_Script.ScriptScript = scriptRepository.GetDataById(test_Script.ScriptId).ToList().First();
         return  test_Script;      
      }
  
     
      public static Test_Script IncludeTestTest(this Test_Script test_Script, ITestRepository testRepository) 
      {
         if (test_Script.TestTest != null) return  test_Script;   
               test_Script.TestTest = testRepository.GetDataById(test_Script.TestId).ToList().First();
         return  test_Script;      
      }
     
  }    
}    
