//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//-----------------------------------------------------------------------------

using System.Linq;
using LucentDb.Data.Repository;

namespace LucentDb.Domain.Entities.Extensions
{
    public static class TestExtensions
    {
        public static Test IncludeProject(this Test test, IProjectRepository projectRepository)
        {
            if (test.Project != null) return test;
            test.Project = projectRepository.GetDataByProjectId(test.ProjectId).ToList().First();
            return test;
        }

        public static Test IncludeScripts(this Test test, IScriptRepository scriptRepository)
        {
            if (test.Scripts != null) return test;
            test.Scripts = (ScriptList) scriptRepository.GetScriptsForTestByTestId(test.Id);
            return test;
        }

        public static Test IncludeTestType(this Test test, ITestTypeRepository testTypeRepository)
        {
            if (test.TestType != null) return test;
            test.TestType = testTypeRepository.GetDataById(test.TestTypeId).ToList().First();
            return test;
        }
    }
}