//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//-----------------------------------------------------------------------------
using LucentDb.Data.Repository;
using System.Linq;
  
namespace LucentDb.Domain.Entities.Extensions 
{
  public static class TestTypeExtensions
  {
   
     
      public static TestType IncludeTestsTestType(this TestType testType, ITestRepository testRepository) 
      {
         if (testType.TestsTestType != null) return  testType;   
               testType.TestsTestType = (TestList)testRepository.GetDataByTestTypeId(testType.Id);
         return  testType;      
      }
     
  }    
}    
