//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Generated by Merlin Version: 1.0.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//-----------------------------------------------------------------------------
using LucentDb.Data.Repository;
using System.Linq;
  
namespace LucentDb.Domain.Entities.Extensions 
{
  public static class TestGroupExtensions
  {
   
     
      public static TestGroup IncludeTests(this TestGroup testGroup, ITestRepository testRepository) 
      {
         if (testGroup.Tests != null) return  testGroup;   
               testGroup.Tests = (TestList)testRepository.GetDataByGroupId(testGroup.Id);
         return  testGroup;      
      }
  
     
      public static TestGroup IncludeProject(this TestGroup testGroup, IProjectRepository projectRepository) 
      {
         if (testGroup.Project != null) return  testGroup;   
               testGroup.Project = projectRepository.GetDataByProjectId(testGroup.ProjectId).ToList().First();
         return  testGroup;      
      }
     
  }    
}    
