'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Generated by Merlin Version: 1.0.0.0
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.ComponentModel
Imports System.Data
Imports LucentDb.Data.DbCommandProvider
Imports LucentDb.Domain.Entities


Namespace LucentDb.Data.Repository
    <DataObject(true)>
    Public Class DbConnectionProviderRepository
        Implements IConnectionProviderRepository
        Implements IDisposable

        Private ReadOnly _dbConnectionProviderCommandProvider As IDbConnectionProviderCommandProvider
        Private _dbConnHolder As DbConnectionHolder = Nothing

        Public Sub New(dbConnectionProviderCommandProvider As IDbConnectionProviderCommandProvider)
            _dbConnectionProviderCommandProvider = dbConnectionProviderCommandProvider
            _dbConnHolder = _dbConnectionProviderCommandProvider.ConnectionProviderDbConnectionHolder
        End Sub

        Public Function GetData() as ICollection(Of ConnectionProvider) Implements IConnectionProviderRepository.GetData
            Dim command As IDbCommand = _dbConnectionProviderCommandProvider.GetGetDataDbCommand()
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
            Dim entList as new Collection(Of ConnectionProvider)
            Dim reader As New SafeDataReader(command.ExecuteReader(CommandBehavior.CloseConnection))
            Do While (reader.Read())
                Dim _
                    tempEntity As _
                        New ConnectionProvider(reader.GetInt32("Id"), reader.GetString("Name"),
                                               reader.GetString("Value"))
                entList.Add(tempEntity)
            Loop
            reader.Close
            Return entList
        End Function

        Public Sub Update(name As String, value As String, id As Int32) Implements IConnectionProviderRepository.Update
            Dim command As IDbCommand = _dbConnectionProviderCommandProvider.GetUpdateDbCommand(Name, Value, Id)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
            Command.ExecuteNonQuery
            _dbConnHolder.Close()
        End Sub

        Public Sub Update(connectionProvider as ConnectionProvider) Implements IConnectionProviderRepository.Update
            With ConnectionProvider
                Update(CStr(.Name), CStr(.Value), CInt(.Id))
            End With
        End Sub

        Public Sub Delete(id As Int32) Implements IConnectionProviderRepository.Delete
            Dim command As IDbCommand = _dbConnectionProviderCommandProvider.GetDeleteDbCommand(Id)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
            Command.ExecuteNonQuery
            _dbConnHolder.Close()
        End Sub

        Public Sub Delete(connectionProvider as ConnectionProvider) Implements IConnectionProviderRepository.Delete
            With ConnectionProvider
                Delete(CInt(.Id))
            End With
        End Sub

        Public Function Insert(name As String, value As String) as Int32 Implements IConnectionProviderRepository.Insert
            Dim command As IDbCommand = _dbConnectionProviderCommandProvider.GetInsertDbCommand(Name, Value)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
            Dim returnValue As Int32 = Convert.ToInt32(Command.ExecuteScalar())
            _dbConnHolder.Close()
            Return returnValue
        End Function

        Public Function Insert(connectionProvider as ConnectionProvider) as Int32 _
            Implements IConnectionProviderRepository.Insert
            With ConnectionProvider
                Return Insert(CStr(.Name), CStr(.Value))
            End With
        End Function

        Public Function GetDataPageable(sortExpression As String, page As Int32, pageSize As Int32) _
            as PagedResult(Of ConnectionProvider) Implements IConnectionProviderRepository.GetDataPageable
            Dim command As IDbCommand = _dbConnectionProviderCommandProvider.GetGetDataPageableDbCommand(sortExpression,
                                                                                                         page, pageSize)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
            Dim entList as new Collection(Of ConnectionProvider)
            Dim reader As New SafeDataReader(command.ExecuteReader(CommandBehavior.CloseConnection))
            Do While (reader.Read())
                Dim _
                    tempEntity As _
                        New ConnectionProvider(reader.GetInt32("Id"), reader.GetString("Name"),
                                               reader.GetString("Value"))
                entList.Add(tempEntity)
            Loop
            reader.Close
            Dim totalCount as Int64 = GetRowCount()
            Dim pagedResults as PagedResult(Of ConnectionProvider) = New PagedResult(Of ConnectionProvider)(page,
                                                                                                            pageSize,
                                                                                                            totalCount,
                                                                                                            entList)
            Return pagedResults
        End Function

        Public Function GetRowCount() as Int32
            Dim command As IDbCommand = _dbConnectionProviderCommandProvider.GetGetRowCountDbCommand()
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
            Dim returnValue As Int32 = Convert.ToInt32(Command.ExecuteScalar())
            _dbConnHolder.Close()
            Return returnValue
        End Function

        Public Function GetDataById(id As Int32) as ICollection(Of ConnectionProvider) _
            Implements IConnectionProviderRepository.GetDataById
            Dim command As IDbCommand = _dbConnectionProviderCommandProvider.GetGetDataByIdDbCommand(Id)
            command.Connection = _dbConnHolder.Connection
            _dbConnHolder.Open()
            Dim entList as new Collection(Of ConnectionProvider)
            Dim reader As New SafeDataReader(command.ExecuteReader(CommandBehavior.CloseConnection))
            Do While (reader.Read())
                Dim _
                    tempEntity As _
                        New ConnectionProvider(reader.GetInt32("Id"), reader.GetString("Name"),
                                               reader.GetString("Value"))
                entList.Add(tempEntity)
            Loop
            reader.Close
            Return entList
        End Function


#Region "IDisposable Support"

        Private disposedValue As Boolean

        Protected Overridable Sub Dispose(disposing As Boolean)
            If Not Me.disposedValue Then
                If disposing Then
                    Select Case _dbConnHolder.Connection.State
                        Case ConnectionState.Open
                            _dbConnHolder.Close()
                    End Select
                    _dbConnHolder = Nothing
                End If

            End If
            Me.disposedValue = True
        End Sub

        Public Sub Dispose() Implements IDisposable.Dispose
            Dispose(True)
            GC.SuppressFinalize(Me)
        End Sub

#End Region
    End Class
End NameSpace
